name: PluginTemplate
version: '1.0-SNAPSHOT'
main: com.goottsy.PluginTemplate
api-version: '1.19'
authors: [ Goottsy ]
description: Un plugin con muchas cosas de ...
website: https://twitter.com/Goottsy